### ISSUE TITLE
Using NQ materials only to speed up entering next craft

### ISSUE THREAD

**Issue by mmaine** [nvll/xivtools#6] opened 2019-08-02 21:08 UTC
Not sure if you're taking enhancements (although it's a tag so I figured I'd add) but here's something small;

Allowing the selection of NQ only which would skip the NQ/HQ ingredient selection process(since they are always selected if you have all NQ on-hand) to speed up the next craft. Current BiS crafting sets do not require any HQ materials to produce HQ items and could on longer craft sessions potentially reduce crafting time.

**Comment by nvll** [comment] 2019-08-02 21:32
Hi, I appreciate the feedback!

I'm not sure if you've run the latest release, but here's the current staging branch in action: https://www.youtube.com/watch?v=neSoWRJTPf

Choosing all the materials takes less than a second, and will work for any combination regardless of time. Even if the end game recipes can be done with NQ, it's common for a player to have a mix of NQ/HQ via gathering nodes. At the current speed of crafting, we'd see significantly better speedups if I tighten some of the other margins, so this option is a bit of a lower priority. That said, there's already an option to specify what the NQ/HQ breakdown is for a given item that I need to finish implementing, so when that's live I think it'll solve your problem since the ingredients default to NQ in the list?
![image](https://user-images.githubusercontent.com/62597/62399939-62ace100-b532-11e9-9502-d28aa8ee0dbe.png) vs 
![image](https://user-images.githubusercontent.com/62597/62399952-693b5880-b532-11e9-9e96-2e1fedbd56ff.png)

Does that seem ok?

**Comment by xaiq** [comment] 2019-08-02 21:54
Ah, video works now!

Yeah I'm on the staging branch(I live for early stuff), and while it indeed shouldn't be of high priority, on items with more materials it eats a ~1.5 seconds on a item with 5 ingredients. While not super important, over time if you create large batches of items this can significantly reduce crafting times, and for sure isn't a high priority!

For reference from when I recorded and checking recording:

16.350s enter material selection
17.817s synthesize was clicked

While not a massive deal, 1.467 seconds every 60 crafts already would shave 87 seconds (unless I'm really, really bad with math which I'm positive could be a case) which (with <wait.x> macros) would net in 2 extra crafts(almost 3) for my tincture collectible crafts.

The material selection otherwise is fine in my opinion, but having a option to skip the material selection when looking to min-max time as a crafter on large batches would speed up, and definitely, only is a nitpick time saver. I wouldn't waste energy or time at this early point on something like this, but I felt it was reasonable enough to validate as an enhancement for the possible future!

**Comment by nvll** [comment] 2019-08-03 20:14
Tracked in #8

**Comment by nvll** [comment] 2019-08-07 16:48
Duplicate of #8

**Closed by nvll** 2019-08-07 16:48 UTC
Labels: enhancement
