### ISSUE TITLE
Missing "macros" folder prevents talan.exe from running

### ISSUE THREAD

**Issue by Onibus** [nvll/xivtools#25] opened 2019-08-11 16:09 UTC
First off, amazing job for a beta build! As someone who has been interested in learning RUST, I'm enjoying looking through the code and learning how things work. Keep up the awesome job!

OS: Windows
Build: a5edfc62d6f4d22645fd5553781a9253027dc48d

When building from source using `cargo build --release` or equivalent, the following top-level structure is created
 
```
C:.
│   .cargo-lock
│   talan.d
│   talan.exe
│   talan.pdb
│
├───.fingerprint
├───build
├───deps
├───examples
├───incremental
└───native
```

If you attempt to run `talan.exe` from location `C:\...\GitHub\xivtools\target\release` with CMD or PS , the following error appears:
`Error: Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." }`

Using procmon, Talan.exe is attempting to check for `/macros` directory but fails to find it.
![image](https://user-images.githubusercontent.com/6449080/62836395-3e3abe00-bc30-11e9-9c8d-6bb02ae753c0.png)
Manually adding it allows `Talan.exe` to run as expected. Perhaps if the directory is not found, create it and stuff in a default macro file?

**Comment by nvll** [comment] 2019-08-12 00:31
Duplicate of #9, tracked there.

**Closed by nvll** 2019-08-12 00:31 UTC
