### ISSUE TITLE
Itemsearch with multiple items of the same name fails to pick the correct craft

### ISSUE THREAD

**Issue by mmaine** [nvll/xivtools#22] opened 2019-08-07 14:56 UTC
Items that come up with multiple items with one search do not seem to work.

The leatherworking item "Swallowskin Shoes" is a example, when it attempts to Craft the first one in the list. The GUI has no way to distinguish which of the list to use like the CLI had the option for.

**Comment by nvll** [comment] 2019-08-07 15:09
Duplicate of #17

**Closed by nvll** 2019-08-07 15:09 UTC

**Comment by nvll** [comment] 2019-08-07 15:15
Duplicate #16
